### PR TITLE
Input argument validation

### PR DESCRIPTION
**Pull request by Horschig**
Dear Homer3 team,

in collaboration with Vijay from the Mathworks team, we have worked on some Homer3 improvements. This is the first pull request which we are making. It is featuring the new input validation feature of Matlab (https://www.mathworks.com/help/matlab/matlab_prog/function-argument-validation-1.html). 

Note that the syntax is not supported by older Matlab versions. Vijay would like to chime here, so I will notify him.

### CODE REVIEW

**Comment by sstucker** [comment]
Thank you for this excellent contribution.

I have the following comments on the code:

It would be better to refactor the `isExpectedClass` function into a separate function, perhaps in Utils.

This would require that the new release target 2021b... This should be okay? @jayd1860

**Comment by vijayiyer05** [comment]
@sstucker  Glad function argument validation is appearing a useful direction to make Homer code more readable and robust. 

Regarding minimum version, did you identify a particular aspect that needed R2021b? Function argument validation was first introduced in R2017a. The most recent validation functions appear to have been [added in R2020b](https://www.mathworks.com/help/matlab/release-notes.html?category=language-programming&rntext=&startrelease=R2017a&endrelease=R2021b&groupby=release&sortby=descending&searchHighlight=).

**Comment by sstucker** [comment]
@vijayiyer05 Ah, okay. I am only concerned with the dependence of this code. Which is > 2017a?

**Comment by vijayiyer05** [comment]
@sstucker That makes sense. Can't say for sure since I haven't analyzed to see if there's a dependency on a newer validation function. My suggestion would be to try the [Code Compatibility Report](https://www.mathworks.com/help/matlab/matlab_prog/matlab-code-compatibility-report.html) feature/function to help make the determination.

**Comment by Horschig** [comment]
> Thank you for this excellent contribution.
> 
> I have the following comments on the code:
> 
> It would be better to refactor the `isExpectedClass` function and any other repeated code into a separate function, perhaps in Utils.
> 
> This would require that the new release target 2021b... This should be okay? @jayd1860

That is an excellent suggestion. However, you guys have to decide whether you want this in at all, because the syntax breaks backwards compatibility:

image

If you are planning to accept this PR, then we are happy to refactor. Otherwise, it'd be a waste of time obviously ;)

**Comment by Horschig** [comment]
> @vijayiyer05 Ah, okay. I am only concerned with the dependence of this code. Which is > 2017a?

I think it is 2021b:

image

**Comment by vijayiyer05** [comment]
@Horschig: this version number at top simply indicates which version of the documentation this is. By default, one looks at the latest. 

To see when a feature was introduced, one can look at a specific function doc page and scroll to *the bottom* to see what version introduced it. 

Above I noted that [validation functions](https://www.mathworks.com/help/matlab/matlab_prog/argument-validation-functions.html) were introduced in R2017a. 

Looking a bit closer, this was initially for class properties. It seems the [arguments block](https://www.mathworks.com/help/matlab/ref/arguments.html) for functions was introduced in R2019b. 

So *2019b* should be the min version dependency to incorporate this. There were some new validators introduced in R2020b, but those are for convenience and not an essential dependency. 

Note that I generally recommend keeping a "future" branch that includes a mix of things that are improvements for the developers and users respectively. When you have something that's enough of an enticement for a new user to upgrade Homer, I think that's the best time to ask them to update their foundations as well.

**Comment by sstucker** [comment]
I strongly think we should shelve any changes that require an update beyond 2017b for now. Anything else would be great to get merged.

**Comment by dboas** [comment]
@Horschig 
I could go ahead and approve this. It looks okay to me. Can you just double check it and confirm you want me to proceed with this. We are getting back on top of things here.

**Comment by Horschig** [comment]
Thanks for getting back to this. I think it is up to you. This change breaks backwards compatibility with older Matlab versions, from what I see Matlab 2019b or newer will be required. I cannot judge whether you want that, as it might result in numerous support questions like "why does Homer gives an error". On the other hand, it would simplify the code, make it more robus and make maintenance somewhat easier. Your call, I won't be mad either way ;)

**Comment by dboas** [comment]
We are fine not supporting before 2019b
Thx


From: Sreekanth kura ***@***.***>
Date: Wednesday, January 17, 2024 at 2:14 PM
To: BUNPC/Homer3 ***@***.***>
Cc: Boas, David ***@***.***>, Comment ***@***.***>
Subject: Re: [BUNPC/Homer3] Input argument validation (PR #104)

Merged #104<https://github.com/BUNPC/Homer3/pull/104> into development.

**Pull request merged**
